import { IExpense } from '../../../app/models/expenses';
import { BehaviorSubject } from 'rxjs';

export const expenses = new BehaviorSubject<IExpense[]>([]);

export const sampleData: IExpense[] = [
  {
    Date: '08/25/2022',
    Merchant: 'Fast food',
    Total: '$55.38',
    Status: 'New',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/25/2022',
    Merchant: 'Ride sharing',
    Total: '$106.31',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/25/2022',
    Merchant: 'Restaurant',
    Total: '$63.58',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/25/2022',
    Merchant: 'Office supplies',
    Total: '$508.09',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/25/2022',
    Merchant: 'Restaurant',
    Total: '$30.99',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/25/2022',
    Merchant: 'Shuttle',
    Total: '$214.35',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/25/2022',
    Merchant: 'Electronics',
    Total: '$94.59',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/25/2022',
    Merchant: 'Hotel',
    Total: '$89.74',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/25/2022',
    Merchant: 'Breakfast',
    Total: '$240.79',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/25/2022',
    Merchant: 'Airline',
    Total: '$127.04',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/25/2022',
    Merchant: 'Office supplies',
    Total: '$32.60',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/24/2022',
    Merchant: 'Parking',
    Total: '$15.99',
    Status: 'In Progress',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/24/2022',
    Merchant: 'Office supplies',
    Total: '$764.03',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/24/2022',
    Merchant: 'Office supplies',
    Total: '$74.53',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/24/2022',
    Merchant: 'Ride sharing',
    Total: '$253.04',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/24/2022',
    Merchant: 'Electronics',
    Total: '$32.12',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/24/2022',
    Merchant: 'Shuttle',
    Total: '$18.04',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/24/2022',
    Merchant: 'Fast food',
    Total: '$542.16',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/24/2022',
    Merchant: 'Parking',
    Total: '$595.14',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/24/2022',
    Merchant: 'Hotel',
    Total: '$249.47',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/24/2022',
    Merchant: 'Breakfast',
    Total: '$404.34',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/24/2022',
    Merchant: 'Office supplies',
    Total: '$167.00',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/24/2022',
    Merchant: 'Office supplies',
    Total: '$549.54',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/24/2022',
    Merchant: 'Rental car',
    Total: '$245.29',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/24/2022',
    Merchant: 'Ride sharing',
    Total: '$255.75',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/24/2022',
    Merchant: 'Rental car',
    Total: '$172.12',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/24/2022',
    Merchant: 'Office supplies',
    Total: '$530.36',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/24/2022',
    Merchant: 'Restaurant',
    Total: '$558.14',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/24/2022',
    Merchant: 'Fast food',
    Total: '$34.43',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/24/2022',
    Merchant: 'Shuttle',
    Total: '$29.34',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/24/2022',
    Merchant: 'Fast food',
    Total: '$62.78',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/24/2022',
    Merchant: 'Parking',
    Total: '$15.38',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/23/2022',
    Merchant: 'Office supplies',
    Total: '$416.30',
    Status: 'In Progress',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/23/2022',
    Merchant: 'Rental car',
    Total: '$66.86',
    Status: 'In Progress',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/23/2022',
    Merchant: 'Airline',
    Total: '$17.33',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/23/2022',
    Merchant: 'Fast food',
    Total: '$61.72',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/23/2022',
    Merchant: 'Shuttle',
    Total: '$516.16',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/23/2022',
    Merchant: 'Parking',
    Total: '$160.72',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/23/2022',
    Merchant: 'Office supplies',
    Total: '$89.88',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/23/2022',
    Merchant: 'Fast food',
    Total: '$15.11',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/23/2022',
    Merchant: 'Rental car',
    Total: '$94.45',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/23/2022',
    Merchant: 'Parking',
    Total: '$188.08',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/23/2022',
    Merchant: 'Hotel',
    Total: '$188.44',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/23/2022',
    Merchant: 'Office supplies',
    Total: '$89.02',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/23/2022',
    Merchant: 'Shuttle',
    Total: '$10.51',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/23/2022',
    Merchant: 'Taxi',
    Total: '$41.70',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/23/2022',
    Merchant: 'Airline',
    Total: '$22.32',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/23/2022',
    Merchant: 'Electronics',
    Total: '$543.36',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/22/2022',
    Merchant: 'Rental car',
    Total: '$346.16',
    Status: 'New',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/22/2022',
    Merchant: 'Electronics',
    Total: '$562.65',
    Status: 'New',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/22/2022',
    Merchant: 'Airline',
    Total: '$215.20',
    Status: 'In Progress',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/22/2022',
    Merchant: 'Parking',
    Total: '$181.13',
    Status: 'In Progress',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/22/2022',
    Merchant: 'Breakfast',
    Total: '$583.31',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/22/2022',
    Merchant: 'Restaurant',
    Total: '$37.13',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/22/2022',
    Merchant: 'Rental car',
    Total: '$118.31',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/22/2022',
    Merchant: 'Breakfast',
    Total: '$329.49',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/22/2022',
    Merchant: 'Hotel',
    Total: '$24.29',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/22/2022',
    Merchant: 'Office supplies',
    Total: '$163.39',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/22/2022',
    Merchant: 'Fast food',
    Total: '$198.50',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/22/2022',
    Merchant: 'Electronics',
    Total: '$247.86',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/22/2022',
    Merchant: 'Office supplies',
    Total: '$130.44',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/22/2022',
    Merchant: 'Breakfast',
    Total: '$42.93',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/22/2022',
    Merchant: 'Shuttle',
    Total: '$579.59',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/22/2022',
    Merchant: 'Parking',
    Total: '$44.77',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/22/2022',
    Merchant: 'Parking',
    Total: '$117.07',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/21/2022',
    Merchant: 'Hotel',
    Total: '$174.18',
    Status: 'New',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/21/2022',
    Merchant: 'Ride sharing',
    Total: '$690.52',
    Status: 'New',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/21/2022',
    Merchant: 'Breakfast',
    Total: '$312.05',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/21/2022',
    Merchant: 'Ride sharing',
    Total: '$182.14',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/21/2022',
    Merchant: 'Taxi',
    Total: '$212.35',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/21/2022',
    Merchant: 'Rental car',
    Total: '$13.59',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/21/2022',
    Merchant: 'Parking',
    Total: '$299.29',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/21/2022',
    Merchant: 'Taxi',
    Total: '$28.73',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/21/2022',
    Merchant: 'Restaurant',
    Total: '$88.06',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/21/2022',
    Merchant: 'Taxi',
    Total: '$51.23',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/21/2022',
    Merchant: 'Parking',
    Total: '$397.95',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/22/2022',
    Merchant: 'Hotel',
    Total: '$24.29',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/22/2022',
    Merchant: 'Office supplies',
    Total: '$163.39',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/22/2022',
    Merchant: 'Fast food',
    Total: '$198.50',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/22/2022',
    Merchant: 'Electronics',
    Total: '$247.86',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/22/2022',
    Merchant: 'Office supplies',
    Total: '$130.44',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/22/2022',
    Merchant: 'Breakfast',
    Total: '$42.93',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/22/2022',
    Merchant: 'Shuttle',
    Total: '$579.59',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/22/2022',
    Merchant: 'Parking',
    Total: '$44.77',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/22/2022',
    Merchant: 'Parking',
    Total: '$117.07',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/21/2022',
    Merchant: 'Hotel',
    Total: '$174.18',
    Status: 'New',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/21/2022',
    Merchant: 'Ride sharing',
    Total: '$690.52',
    Status: 'New',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/21/2022',
    Merchant: 'Breakfast',
    Total: '$312.05',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/21/2022',
    Merchant: 'Ride sharing',
    Total: '$182.14',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/21/2022',
    Merchant: 'Taxi',
    Total: '$212.35',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/21/2022',
    Merchant: 'Rental car',
    Total: '$13.59',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/21/2022',
    Merchant: 'Parking',
    Total: '$299.29',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/21/2022',
    Merchant: 'Taxi',
    Total: '$28.73',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/21/2022',
    Merchant: 'Restaurant',
    Total: '$88.06',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/21/2022',
    Merchant: 'Taxi',
    Total: '$51.23',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/21/2022',
    Merchant: 'Parking',
    Total: '$397.95',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/21/2022',
    Merchant: 'Breakfast',
    Total: '$359.08',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/21/2022',
    Merchant: 'Airline',
    Total: '$34.12',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/20/2022',
    Merchant: 'Rental car',
    Total: '$108.50',
    Status: 'New',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/20/2022',
    Merchant: 'Restaurant',
    Total: '$251.64',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/20/2022',
    Merchant: 'Shuttle',
    Total: '$315.19',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/20/2022',
    Merchant: 'Parking',
    Total: '$472.55',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/20/2022',
    Merchant: 'Office supplies',
    Total: '$88.18',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/20/2022',
    Merchant: 'Electronics',
    Total: '$749.78',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/20/2022',
    Merchant: 'Taxi',
    Total: '$710.31',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/20/2022',
    Merchant: 'Electronics',
    Total: '$105.84',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/19/2022',
    Merchant: 'Parking',
    Total: '$262.18',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/19/2022',
    Merchant: 'Hotel',
    Total: '$10.61',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/19/2022',
    Merchant: 'Taxi',
    Total: '$332.15',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/19/2022',
    Merchant: 'Taxi',
    Total: '$497.51',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/19/2022',
    Merchant: 'Ride sharing',
    Total: '$59.90',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/19/2022',
    Merchant: 'Taxi',
    Total: '$330.11',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/19/2022',
    Merchant: 'Parking',
    Total: '$405.91',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/19/2022',
    Merchant: 'Airline',
    Total: '$94.54',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/19/2022',
    Merchant: 'Restaurant',
    Total: '$103.82',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/19/2022',
    Merchant: 'Fast food',
    Total: '$66.46',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/19/2022',
    Merchant: 'Rental car',
    Total: '$175.48',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/18/2022',
    Merchant: 'Office supplies',
    Total: '$350.63',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/18/2022',
    Merchant: 'Electronics',
    Total: '$146.59',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
  {
    Date: '08/18/2022',
    Merchant: 'Restaurant',
    Total: '$97.79',
    Status: 'Reimbursed',
    Comment: 'Expense from my business trip.',
  },
];

expenses.next(sampleData);
